import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
    },
    header: {
      backgroundColor: '#075E54',
      paddingHorizontal: 20,
      paddingVertical: 15,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 50,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#fff',
    },
    headerIcons: {
      flexDirection: 'row',
    },
    headerIcon: {
      marginLeft: 20,
    },
    searchContainer: {
      backgroundColor: '#075E54',
      paddingHorizontal: 20,
      paddingBottom: 15,
    },
    searchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fff',
      borderRadius: 25,
      paddingHorizontal: 15,
      height: 40,
    },
    searchInput: {
      flex: 1,
      marginLeft: 10,
      fontSize: 14,
      color: '#000',
    },
    adminTalkSection: {
      backgroundColor: '#f5f5f5',
      marginHorizontal: 15,
      marginTop: 10,
      marginBottom: 15,
      borderRadius: 15,
      padding: 16,
      borderWidth: 1,
      borderColor: '#e0e0e0',
    },
    adminTalkHeader: {
      flexDirection: 'row',
    },
    adminTalkIconContainer: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: '#E8F5E9',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    adminTalkInfo: {
      flex: 1,
    },
    adminTalkTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#075E54',
      marginBottom: 6,
    },
    adminTalkDescription: {
      fontSize: 14,
      color: '#666',
      marginBottom: 12,
      lineHeight: 20,
    },
    adminTalkFeatures: {
      flexDirection: 'row',
      marginBottom: 15,
      flexWrap: 'wrap',
    },
    featureItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 15,
      marginBottom: 5,
    },
    featureText: {
      fontSize: 12,
      color: '#666',
      marginLeft: 4,
    },
    joinButton: {
      backgroundColor: '#075E54',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 20,
      alignSelf: 'flex-start',
    },
    joinButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    chatListHeader: {
      paddingVertical: 10,
      paddingHorizontal: 5,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#666',
    },
    listContainer: {
      paddingHorizontal: 15,
      paddingTop: 10,
    },
    chatItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    adminTalkItem: {
      backgroundColor: '#F9F9F9',
      borderRadius: 10,
      marginBottom: 8,
      paddingHorizontal: 10,
    },
    avatarContainer: {
      position: 'relative',
      marginRight: 15,
    },
    avatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
    },
    avatarPlaceholder: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: '#E8F5E9',
      justifyContent: 'center',
      alignItems: 'center',
    },
    groupAvatar: {
      backgroundColor: '#E3F2FD',
    },
    adminTalkAvatar: {
      backgroundColor: '#FFF3E0',
    },
    avatarText: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#075E54',
    },
    onlineDot: {
      position: 'absolute',
      right: 0,
      bottom: 0,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: '#4CAF50',
      borderWidth: 2,
      borderColor: '#fff',
    },
    adminBadge: {
      position: 'absolute',
      top: -5,
      right: -5,
      backgroundColor: '#FF9800',
      borderRadius: 10,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    adminBadgeText: {
      color: '#fff',
      fontSize: 10,
      fontWeight: 'bold',
    },
    chatInfo: {
      flex: 1,
    },
    chatHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    chatName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#000',
      flex: 1,
    },
    adminTalkName: {
      color: '#075E54',
    },
    chatTime: {
      fontSize: 12,
      color: '#999',
      marginLeft: 10,
    },
    chatFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    lastMessage: {
      fontSize: 14,
      color: '#666',
      flex: 1,
    },
    unreadBadge: {
      backgroundColor: '#075E54',
      borderRadius: 12,
      minWidth: 24,
      height: 24,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 6,
      marginLeft: 10,
    },
    unreadText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: 'bold',
    },
    participantsInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    participantsText: {
      fontSize: 11,
      color: '#999',
      marginLeft: 4,
    },
    fab: {
      position: 'absolute',
      right: 20,
      bottom: 80,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: '#075E54',
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.27,
      shadowRadius: 4.65,
    },
    notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -6,
    backgroundColor: '#FF3B30',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: '#007AFF',
  },
  notificationBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  });
export default styles