// // styles/profile.styles.js
// import { StyleSheet } from "react-native";
// import COLORS from "./color";

// const styles = StyleSheet.create({
//   container: {
//     flex: 1,
//     backgroundColor: COLORS.background,
//     padding: 16,
//     paddingBottom: 0,
//   },
//   loadingContainer: {
//     flex: 1,
//     justifyContent: "center",
//     alignItems: "center",
//     backgroundColor: COLORS.background,
//   },
//   profileHeader: {
//     flexDirection: "row",
//     alignItems: "center",
//     backgroundColor: COLORS.cardBackground,
//     borderRadius: 16,
//     padding: 16,
//     marginBottom: 16,
//     shadowColor: COLORS.black,
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.1,
//     shadowRadius: 8,
//     elevation: 3,
//     borderWidth: 1,
//     borderColor: COLORS.border,
//   },
//   profileImage: {
//     width: 80,
//     height: 80,
//     borderRadius: 40,
//     marginRight: 16,
//   },
//   profileInfo: {
//     flex: 1,
//   },
//   username: {
//     fontSize: 20,
//     fontWeight: "700",
//     color: COLORS.textPrimary,
//     marginBottom: 4,
//   },
//   email: {
//     fontSize: 14,
//     color: COLORS.textSecondary,
//     marginBottom: 4,
//   },
//   memberSince: {
//     fontSize: 12,
//     color: COLORS.textSecondary,
//   },
//   logoutButton: {
//     backgroundColor: COLORS.primary,
//     borderRadius: 12,
//     padding: 12,
//     flexDirection: "row",
//     alignItems: "center",
//     justifyContent: "center",
//     marginBottom: 24,
//     shadowColor: COLORS.black,
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.1,
//     shadowRadius: 4,
//     elevation: 2,
//   },
//   logoutText: {
//     color: COLORS.white,
//     fontWeight: "600",
//     marginLeft: 8,
//   },
//   booksHeader: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     alignItems: "center",
//     marginBottom: 16,
//   },
//   booksTitle: {
//     fontSize: 18,
//     fontWeight: "700",
//     color: COLORS.textPrimary,
//   },
//   booksCount: {
//     fontSize: 14,
//     color: COLORS.textSecondary,
//   },
//   booksList: {
//     paddingBottom: 20,
//   },
//   bookItem: {
//     flexDirection: "row",
//     backgroundColor: COLORS.cardBackground,
//     borderRadius: 12,
//     padding: 12,
//     marginBottom: 12,
//     shadowColor: COLORS.black,
//     shadowOffset: { width: 0, height: 1 },
//     shadowOpacity: 0.1,
//     shadowRadius: 4,
//     elevation: 2,
//     borderWidth: 1,
//     borderColor: COLORS.border,
//   },
//   bookImage: {
//     width: 70,
//     height: 100,
//     borderRadius: 8,
//     marginRight: 12,
//   },
//   bookInfo: {
//     flex: 1,
//     justifyContent: "space-between",
//   },
//   bookTitle: {
//     fontSize: 16,
//     fontWeight: "600",
//     color: COLORS.textPrimary,
//     marginBottom: 4,
//   },
//   ratingContainer: {
//     flexDirection: "row",
//     marginBottom: 4,
//   },
//   bookCaption: {
//     fontSize: 14,
//     color: COLORS.textDark,
//     marginBottom: 4,
//     flex: 1,
//   },
//   bookDate: {
//     fontSize: 12,
//     color: COLORS.textSecondary,
//   },
//   deleteButton: {
//     padding: 8,
//     justifyContent: "center",
//   },
//   emptyContainer: {
//     alignItems: "center",
//     justifyContent: "center",
//     padding: 40,
//     marginTop: 20,
//   },
//   emptyText: {
//     fontSize: 16,
//     fontWeight: "600",
//     color: COLORS.textPrimary,
//     marginTop: 16,
//     marginBottom: 20,
//     textAlign: "center",
//   },
//   addButton: {
//     backgroundColor: COLORS.primary,
//     borderRadius: 12,
//     paddingVertical: 12,
//     paddingHorizontal: 20,
//     shadowColor: COLORS.black,
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.1,
//     shadowRadius: 4,
//     elevation: 2,
//   },
//   addButtonText: {
//     color: COLORS.white,
//     fontWeight: "600",
//     fontSize: 14,
//   },
// });

// export default styles;


import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f9fafb",
  },
  scrollView: {
    flex: 1,
  },
  header: {
    backgroundColor: "#ffffff",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f3f4f6",
    justifyContent: "center",
    alignItems: "center",
  },
  editButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f3f4f6",
    justifyContent: "center",
    alignItems: "center",
  },
  profileInfo: {
    alignItems: "center",
    marginTop: 12,
  },
  avatarContainer: {
    position: "relative",
    marginBottom: 16,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: "#3b82f6",
  },
  changePhotoButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#3b82f6",
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  userName: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 4,
  },
  userUsername: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 8,
  },
  userBio: {
    fontSize: 14,
    color: "#4b5563",
    textAlign: "center",
    paddingHorizontal: 32,
    lineHeight: 20,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 20,
    marginHorizontal: 16,
    marginTop: -20,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statCard: {
    alignItems: "center",
    flex: 1,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1f2937",
    marginTop: 8,
  },
  statLabel: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 4,
  },
  section: {
    marginTop: 24,
    paddingHorizontal: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: 12,
    paddingLeft: 4,
  },
  infoCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  infoLabel: {
    fontSize: 14,
    color: "#6b7280",
  },
  infoValue: {
    fontSize: 14,
    color: "#1f2937",
    fontWeight: "500",
  },
  infoValueMonospace: {
    fontSize: 12,
    color: "#1f2937",
    fontWeight: "500",
    fontFamily: "monospace",
  },
  menuCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  menuLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuText: {
    fontSize: 16,
    color: "#374151",
  },
  dangerText: {
    color: "#ef4444",
  },
  badge: {
    backgroundColor: "#3b82f6",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    minWidth: 28,
    alignItems: "center",
  },
  badgeText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#fee2e2",
    marginHorizontal: 16,
    marginTop: 32,
    paddingVertical: 14,
    borderRadius: 12,
  },
  logoutText: {
    color: "#ef4444",
    fontSize: 16,
    fontWeight: "600",
  },
  versionContainer: {
    alignItems: "center",
    paddingVertical: 24,
  },
  versionText: {
    fontSize: 12,
    color: "#9ca3af",
  },
});